version: "3.9"
services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    volumes:
      - "./services/api:/usr/src/app"
    ports:
      - 5000:5000
    environment:
      - DATABASE_CONNECTION_STRING=Server=db, 1433;Database=MotionPictureDbContext;User=sa;Password=Your_password123;
    depends_on:
      - db
  db:
    build:
      context: ./services/api/db
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
        - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - "/var/opt/mssql/backups"
      - "/var/opt/sqlserver"
      - "/var/opt/mssql"
